server:
  port: 9999
spring:
  ai:
    openai:
      api-key: sk-xXe1WMPjhlVb1aiI1b4c6c8934D8463f9e4b67Ed8718B772
      base-url: https://api.pandarobot.chat/
    mcp:
      client:
        enabled: true
        name: call-mcp-server
        sse:
          connections:
            server1:
              url: http://127.0.0.1:6040

